# WaterMeterKit V1 WiFi Configuration
# Main entry point for WiFi firmware

substitutions:
  default_network: "WiFi"

packages:
  base: !include base.yaml
  wifi: !include wifi.yaml

dashboard_import:
  package_import_url: github://smarthomeshop/watermeterkit/watermeterkit-v1/watermeterkit-wifi.yaml@main
